### ISSUE TITLE
Missing setComponent.

### ISSUE THREAD

**Issue by mustakimpawle** [itzmeanjan/intent#31]
How can I set Component and open startup manager app using it?

**Comment by zj902** [comment]
android_intent has componentName,and it works.  But it does not support returning the result of the launched activity.  So can we add component features ?

**Comment by deviankim** [comment]
@mustakimpawle @zj902 
I made PR #48 
For now, you can use my solution using below codes in pubspec.yaml and dart.
```yaml
#  intent: ^1.4.0
  intent:
    git:
      url: https://github.com/ssk-flutter/intent.git
      ref: feature/introduce-set-component
```

```dart
Intent()
  ..setComponent(packageName: 'xxx.xxx.com', className: 'xxx.xxx.app.IntroActivity')
  ..startActivity();
```
